version: '3.8'

services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./laravel:/var/www/html 
        networks:
            - laravel_network
    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        ports:
            - "8080:80"
        volumes:
            - ./laravel:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network
    db:
        image: mariadb:latest
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=''
            - MYSQL_DATABASE=testDb
            - MYSQL_USER=root 
            - MYSQL_PASSWORD=''
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network
    composer:
        image: composer:latest
        container_name: composer
        working_dir: /var/www/html
        volumes:
            - ./laravel:/var/www/html
        entrypoint: ["composer"]
    artisan:
        image: php:8.2-fpm
        container_name: artisan
        working_dir: /var/www/html
        volumes:
            - ./laravel:/var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge